name: nichecompass-reproducibility
channels:
  - bioconda
  - conda-forge
  - nvidia
dependencies:
  - python=3.9
  - jaxlib=*=*cuda*
  - jax=0.4.13
  - cuda-nvcc
  - pip
  - poetry=1.4.2
  - bedtools=2.30.0
  - geckodriver=0.33.0
  - pip:
    - ipykernel==6.15.3
    - ipywidgets==8.0.2
    - jupyterlab==3.4.7
    - scib_metrics==0.3.3
    - mudata==0.2.2
    - GraphST==1.1.1
    - opencv-python==4.7.0.68
    - openpyxl==3.0.10
    - plottable==0.1.5
    - POT==0.8.2
    - scArches==0.5.9
    - tiledb==0.20.0
    - tiledbsoma==0.1.22
